# Generated by Django 6.0.3 on 2026-03-24 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autobus',
            fields=[
                ('placa', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('capacidad_pasajeros', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pasajero',
            fields=[
                ('dpi', models.IntegerField(max_length=13, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.CharField(max_length=100)),
                ('destino', models.CharField(max_length=100)),
                ('precio', models.IntegerField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_y_hora', models.DateField()),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administracion.autobus')),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administracion.ruta')),
            ],
        ),
        migrations.CreateModel(
            name='Boleto',
            fields=[
                ('numero_asiento', models.IntegerField(primary_key=True, serialize=False)),
                ('pasajero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administracion.pasajero')),
                ('viaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administracion.viaje')),
            ],
        ),
    ]
