# Generated by Django 6.0.3 on 2026-04-06 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Administracion', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='boleto',
            unique_together={('viaje', 'numero_asiento')},
        ),
        migrations.AlterUniqueTogether(
            name='viaje',
            unique_together={('bus', 'fecha_y_hora')},
        ),
    ]
