# Generated by Django 6.0.3 on 2026-04-06 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administracion', '0002_alter_boleto_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viaje',
            name='fecha_y_hora',
            field=models.DateTimeField(),
        ),
    ]
