# Generated by Django 6.0.3 on 2026-04-06 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Administracion', '0003_alter_viaje_fecha_y_hora'),
    ]

    operations = [
        migrations.RenameField(
            model_name='autobus',
            old_name='capacidad_pasajeros',
            new_name='capacidad',
        ),
    ]
