# Generated by Django 6.0.3 on 2026-04-06 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administracion', '0004_rename_capacidad_pasajeros_autobus_capacidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruta',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
