# Generated by Django 6.0.3 on 2026-04-06 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administracion', '0005_alter_ruta_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pasajero',
            name='dpi',
            field=models.DecimalField(decimal_places=0, max_digits=13, primary_key=True, serialize=False),
        ),
    ]
