# Generated by Django 6.0.3 on 2026-04-06 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administracion', '0006_alter_pasajero_dpi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pasajero',
            name='dpi',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
