# Generated by Django 6.0.3 on 2026-04-06 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administracion', '0007_alter_pasajero_dpi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pasajero',
            name='dpi',
            field=models.IntegerField(max_length=13, primary_key=True, serialize=False),
        ),
    ]
